version: "3.4"

services:
  nginx_with_preload:
    image: nginx:latest
    container_name: nginx_with_preload
    depends_on:
      - phpfpm_with_preload
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx_with_preload.conf:/etc/nginx/conf.d/default.conf:cached

  nginx_without_preload:
    image: nginx:latest
    container_name: nginx_without_preload
    depends_on:
      - phpfpm_without_preload
    ports:
      - "8002:80"
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx_without_preload.conf:/etc/nginx/conf.d/default.conf:cached

  phpfpm_with_preload:
    build:
      context: ./docker/phpfpm
    container_name: phpfpm_with_preload
    expose:
      - 9000
    volumes:
      - .:/var/www/html:cached
      - ./docker/phpfpm/with-preload/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:cached
      - ./log:/var/log

  phpfpm_without_preload:
    build:
      context: ./docker/phpfpm
    container_name: phpfpm_without_preload
    expose:
      - 9000
    volumes:
      - .:/var/www/html:cached
      - ./docker/phpfpm/without-preload/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:cached
